### ISSUE TITLE
oModel.attachRejectChanges crashes (ex4_24)

### ISSUE THREAD

**Issue by kranz** [SAP/com.sap.openSAP.hana5.templates#3]
In the init function in Component.js there is a call to oModel.attachRejectChanges that makes the application crash.

```
oModel.attachRejectChange(this,function(oEvent){
    sap.m.MessageBox.alert("You are already editing another Entry! Please submit or reject your pending changes!");
}); 
```

The only way to have the app working is to comment it out.
Also, by checking the oDataModel reference at 
https://sapui5.hana.ondemand.com/docs/api/symbols/sap.ui.model.odata.v2.ODataModel.html
there is nothing written about this method, it seems to be non-existent.
Is it correct to just comment it out or should it be replaced with something else?

**Comment by jung-thomas** [comment]
You are correct the attachRejectChange is left over from the older version of the exercise that didn't use the v2 version of the OData Model object.  It was removed from the example implementation (https://github.com/SAP/com.sap.openSAP.hana5.example/blob/dec2016/web/resources/odataCRUD/Component.js) but not from the template.  I've adjusted.
