### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jmalla** [SAP/com.sap.openSAP.hana5.templates#8]
Hi Thomas,

We found a typo - it should be ISO.CURRENCY_CODES instead of ISO.CURRNECY_CODES:

  "ISO.CURRNECY_CODES": {
    "target": {
      "grantor" : "central-db-service",     
      "object": "ISO.CURRNECY_CODES"
    }

Regards,
Jay

**Comment by jung-thomas** [comment]
Actually this is not incorrect.  The target object really is ISO.CURRNECY_CODES. You might not like this name, but that doesn't make the synonym incorrect.
